# Generated by Django 2.0.6 on 2018-06-20 19:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('urgency', models.CharField(default='Meh', max_length=20)),
                ('is_completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TotoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyric', models.CharField(max_length=200)),
                ('song', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='toto_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.TotoItem'),
        ),
    ]
