# Generated by Django 2.0.6 on 2018-06-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180620_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='list_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='list_name',
            new_name='name',
        ),
    ]
